name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: http://10.13.66.5:20091/actions/checkout@v6
      - name: Set up Python
        uses: http://10.13.66.5:20091/actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: python -m pip install --upgrade uv
      - name: Sync dependencies
        run: uv sync
      - name: Compile check
        run: uv run -- python -m compileall src
